storage:
  pinecone:
    index_name: "llamaindex"
    dimension: 768
    metric: "cosine"
    cloud: "aws"
    region: "us-east-1"
  
  mongodb:
    db_name: "llamaindex"
    summary_index:
      collection_name: "summary_index"
      namespace: "summary"
    tree_index:
      collection_name: "tree_index"
      namespace: "tree"
    keyword_index:
      collection_name: "keyword_index"
      namespace: "keyword"
  
  neo4j:
    database: "75565d13"
    index_name: "property_graph"
    text_node_property: "text"
    hybrid_search: false
